### ISSUE TITLE
Use AppMenu instead of custom Ubuntu Budgie button on headerbar

### ISSUE THREAD

**Issue by HEXcube** [UbuntuBudgie/budgie-welcome#104]
Budgie Welcome currently uses a custom button with a hardcoded Ubuntu Budgie icon. On clicking the button, `About` dialog is shown. This is how the headerbar looks like currently:

**Current**:

![budgie welcome with custom button](https://cloud.githubusercontent.com/assets/3755396/24581629/bd0baf00-173c-11e7-84f7-3227a779e4f8.png)

-------

**After**:

I think it's better to use a standard AppMenu instead of this custom button. If AppMenu's enabled, this is how it'd look after bit of a cleanup:

![budgie welcome with appmenu](https://cloud.githubusercontent.com/assets/3755396/24581855/fbe6e10a-1740-11e7-851d-59abe8d83910.png)

The AppMenu icon'd be provided by system icon theme, so no need to bundle hardcoded icon too :smile:

**Comment by fossfreedom** [comment]
App menus are now dead
