### ISSUE TITLE
Add option to set Window Buttons to left

### ISSUE THREAD

**Issue by HEXcube** [UbuntuBudgie/budgie-welcome#107]
Include an option to let users select the position of window buttons. They can be changed to left via gsettings:

```sh
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'close,minimize,maximize,menu:'>}"
gsettings set com.solus-project.budgie-wm button-layout 'close,maximize,minimize,appmenu:'
```

and back to right with:

```sh
gsettings reset org.gnome.settings-daemon.plugins.xsettings overrides
gsettings reset com.solus-project.budgie-wm button-layout
```

Unfortunately, Chrome/Chromium still uses the outdated gconf and so needs a separate command:

```sh
gconftool-2 --set /apps/metacity/general/button_layout --type string "close,minimize,maximize:"
```

and for resetting:

```sh
gconftool-2 --unset /apps/metacity/general/button_layout
```

**Comment by niyasc** [comment]
I would like to get some insights for the window controls positioning option.
- Can we use 4 *select* options with values?
  - AppMenu
  - Minimize
  - Maximize
  - Close
  - None
- First *option* box will be shown be default.
- When we select *option* in first one, second will be shown with all options except option selected in first one, and so on.
- Finally, after choosing all 4 options **apply** button will be made visible.
- The separator `:` can be made draggable.

We can't display currently configured option as we have to gsettings fields and both can have different values.

**Comment by HEXcube** [comment]
> Can we use 4 select options with values?

So, u mean an option to select the position of each window button separately? :confused: I was thinking of a single option/switch (left ot right) that changes just the position of these 3 buttons (close, minimize and maximize) together. AppMenu remains on the left no matter what.

> The separator : can be made draggable.

A drag n' drop UI for changing button positions?

**Comment by niyasc** [comment]
> I was thinking of a single option/switch (left ot right) that changes just the position of these 3 buttons

Then we'll have to show both *show on left* and *show own right* actions simultaneously. Because existing configuration can be either left, or right or a mix of both.

**Comment by niyasc** [comment]
![screenshot from 2017-04-09 19-40-44](https://cloud.githubusercontent.com/assets/2451833/24837926/7fe9e3fa-1d5c-11e7-8ac7-d0e85fb8fa3c.png)

Implemented support for switching window control button positions.

**Comment by fossfreedom** [comment]
+1 all seems to be working.  Good work here :)

Just need to verify non GTK3 apps like chromium, libreoffice and QT apps then  will close - although if any of these dont work doubtful we can actually doing anything anyway.

**Comment by fossfreedom** [comment]
well - would you adam-and-eve-it ... v10.3 of budgie-desktop will now have the ability via Raven to switch windows controls left and right.

**Comment by HEXcube** [comment]
Yeah, like @fossfreedom mentioned, Ikey's decided to implement this option in Raven! :smiley: See https://github.com/budgie-desktop/budgie-desktop/issues/716#issuecomment-292950369

**Comment by HEXcube** [comment]
> Just need to verify non GTK3 apps like chromium, libreoffice and QT apps

Works on LibreOffice coz it behaves just like a GTK2 app. The Qt and KDE Apps I've used do respect the setting. About Chrome/Chromium, either it needs to be set to use native window decorations or this gconf key needs to be set:

```
gconftool-2 --set /apps/metacity/general/button_layout --type string "close,minimize,maximize:"
```

Chrome still uses the old gconf system instead of gsettings/dconf :confused:

**Comment by fossfreedom** [comment]
really - still gconf?? That is ancient!

maybe @HEXcube also update the budgie-desktop issue with the gconf tool tip so that it also updates that key.

**Comment by HEXcube** [comment]
> really - still gconf?? That is ancient!

Yeah, hard to believe but true. Maybe the new GTK3 build'd update things: [Link to article on OMG!Ubuntu](http://www.omgubuntu.co.uk/2017/03/google-chrome-chromium-gtk3-by-default)

> maybe @HEXcube also update the budgie-desktop issue with the gconf tool tip so that it also updates that key.

K.. I'll add the command for Chrome/Chromium too :+1:

**Comment by fossfreedom** [comment]
now backed out in favour of budgie-desktop 10.3
