### ISSUE TITLE
Installation routines fail

### ISSUE THREAD

**Issue by spectas** [UbuntuBudgie/budgie-welcome#108]
Hello everyone,
the package "budgie-welcome" comes with the great feature to recommend installing applications and for example the (missing) standard themes Arc/Moka. Unfortunately, these installation links do not work (at least with my system configuration). It looks like they are linked to one software center app, but crash with a notification (e.g.: "Welcome app: Failed installation of arc-theme") when this app is missing.

Imho it would be good to use a more abstract approach to installing apps. I encountered another bug report, probably adressing a similar problem. Imho this could be done by using "sudo apt-get install arc-theme". If not preferred (e.h. for user convenciance reasons) this might be a fall back solution if budgie-welcome cannot find the preferred sofware center application.

Thanks a lot for this great desktop!!
Spectas

My configuration:
budgie-desktop 10.2.9
budgie-welcome 0.4.3.1
Linux kernel 4.4.0-53-generic
Linux Mint 18.1. Serena (Xenial)

**Comment by fossfreedom** [comment]
please run `budgie-welcome` from a terminal and try to install stuff.

what is the output you see in the terminal?

**Comment by spectas** [comment]
Hi, the output is:

```
Using /usr/share/budgie-welcome/ path.
Traceback (most recent call last):
  File "/usr/lib/budgie-welcome/budgie-welcome-privileged-actions", line 6, in <module>
    from softwareproperties.SoftwareProperties \
ImportError: No module named 'softwareproperties'
[Apt] Reloading cache... 
[Apt] Cache reloaded.
```

**Comment by fossfreedom** [comment]
if you install `python3-software-properties` does stuff start to work again?

**Comment by spectas** [comment]
No, unfortunately the same result:
```

sp@xyz:~$ sudo apt-get install python3-software-properties
Entpacken von python3-software-properties (1.6.4) ...
python3-software-properties (1.6.4) wird eingerichtet ...

sp@xyz:~$ budgie-welcome
Using /usr/share/budgie-welcome/ path.

Traceback (most recent call last):
  File "/usr/lib/budgie-welcome/budgie-welcome-privileged-actions", line 6, in <module>
    from softwareproperties.SoftwareProperties \
ImportError: No module named 'softwareproperties'

```

**Comment by fossfreedom** [comment]
Have you installed another version of python? maybe installed python from source or from a PPA?

what is the output of `which python3` and the output of `python3 --version` ?

**Comment by spectas** [comment]
```
sp@xyz:~$ which python3
/usr/bin/python3

sp@xyz:~$ python3 --version
Python 3.5.2
```

**Comment by fossfreedom** [comment]
Xenial comes with v3.5.1.  looks like you have ok installed another python version which is not picking up the software properties module

**Comment by fossfreedom** [comment]
closing since this is due to non-standard python install.
