### ISSUE TITLE
Lack of some translation items on transifex

### ISSUE THREAD

**Issue by sebcyg** [UbuntuBudgie/budgie-welcome#109]
For some original English texts there is no translation items, so it is not possible to create translation.
E.g. 
1. "Getting started" screen in the menu on the left there is no translation items for name of categories: "Post-installation", "Familiarity", "Troubleshooting"
2. "Introduction" screen in the fragment "Wikipedia says that a Desktop Environment is" there is no translation item that would allow to translate word "is"

**Comment by fossfreedom** [comment]
thanks - have added these and pushed to transifex.
