### ISSUE TITLE
oddities with the french version of budgie-welcome

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#112]
any ideas on these two issues with the french version of budgie-welcome @niyasc ?

    cd scripts
    ./rebuild-translations.sh
    cd ..
    ./budgie-welcome --locale=fr

The back button for "features" does not actually work.

There doesn't appear to be a sort order of recommendations.

**Comment by niyasc** [comment]
Apparently, there is some minor issue with translation. After translation, we are missing a closing double quotes and it affects the jQuery loading part.

![issue](https://cloud.githubusercontent.com/assets/2451833/25316118/c1fa93c0-287e-11e7-87a0-b191fe10992d.png)

**Comment by fossfreedom** [comment]
good spot for the features @niyasc !!

**Comment by niyasc** [comment]
It was not that difficult.

 I just opened french translated `features.html` file in web browser and checked console log. It was showing `Symbol $ not found error`, which indicates absence of `jQuery`. 

So I examined the html file in `gedit`, which was clearly highlighting the issue with color changes. :smile:

**Comment by fossfreedom** [comment]
Shall remember that one.  

Thoughts on the sort issue?

**Comment by niyasc** [comment]
I will check it in the evening ( > GST 3 PM ).

**Comment by niyasc** [comment]
After translation, **DOM** structure is getting affected. For, budgie screenshot applet, `</strong>` closing tag is missing. Change in **DOM** structure affects sorting functionality.

Following were points supported this inference.
- When we open `recommendation` page for French translation, some of the paragraphs are in bold, which is not the case with original file.
- In original file, there are 9 opening and closing `strong` tags, but in translated file there are 9 opening tags but 8 closing tags.
- After adding `</strong>` tag manually, list is getting sorted as per expectation.

**Comment by fossfreedom** [comment]
thanks.  I can see why the translator ignored that closing strong tag - there was no corresponding opening strong tag.  The &zwnj; should be before the opening strong - not afterwards.

cheers for this.
