### ISSUE TITLE
multiple google repositories added

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#123]
having added - removed - and added chrome  I noticed that multiple google repositories were enabled in the sources listing.

Very odd.

**Comment by niyasc** [comment]
We were facing similar issue while checking the status of `budgie-remix`/`backports` PPA and you had addressed it as follows:

    if repos:
                # for the first element of the codename (e.g. zesty)
                # repo split by the / character to get an array
                # first element is the ppa organisation and second
                # is the ppa name
                ppa = repos[systemstate.codename][0][4:].split('/')

                filename = ppa[0] + "-ubuntu-" + ppa[1] + "-" + \
                    systemstate.codename + ".list"
                filename = '/etc/apt/sources.list.d/' + filename
                print(filename)
                p = subprocess.Popen(['grep', '^deb\ http', filename])
                retval = p.wait()

                if retval == 0:
                    found = True

We can use a similar approach. But it should be generic enough to check for different repositories like

- multiverse/universe within ubuntu repository
- 3rd party PPA's
- 3rd party debian repos, such as chrome repo.

**Comment by fossfreedom** [comment]
fixed in 0.4.9.8
