### ISSUE TITLE
Adapta style background is not available

### ISSUE THREAD

**Issue by niyasc** [UbuntuBudgie/budgie-welcome#124]
Currently Adapta style is using **ubuntu_budgie_wallpaper3.jpg** as wallpaper. However, it is not available in budgie wallpaper directory.

**Note**
Installed budgie-desktop-environment package on Ubuntu GNOME 17.04

**Comment by fossfreedom** [comment]
hmm - the updated budgie-wallpapers is definitely in our backports PPA.

odd.  Is this a local version of budgie-welcome that you are testing?  Will also need to install the backports PPA.

**Comment by niyasc** [comment]
Oh. I missed to install wallpaper package from backport repo :cry:
