### ISSUE TITLE
use tabs to toggle between themes and panel reset

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#125]
@niyasc thinking of using tabs to divide the two areas of default.html 

one tab for generic "tweaks" such as the panel reset
one tab for themes

https://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior

I can't though see to get the example to work - any ideas?  basically any example code would be useful here - then will try to merge in the actual default.html contents.

**Comment by niyasc** [comment]
@fossfreedom
Please check whether this fiddle is working.
https://jsfiddle.net/5acw9thz/

Please make sure that jQuery, tether and bootstrap cdn are loaded properly. If those scripts files are available, tab switching will work without any custom scripts.

**Comment by fossfreedom** [comment]
@niyasc knocked up a test page using the fiddle

opened in firefox - tabs display - but cannot click between the tabs.

thoughts?

https://github.com/UbuntuBudgie/budgie-welcome/commit/179c2fdc5e81fbb96fd79919d1eb410f6c3737f5

**Comment by niyasc** [comment]
Some points to look for:
- Is `bootstrap.min.js` present in `scripts` folder?
- Is there any error in firefox console?

If both are okay, I will check it tonight (> GST 3 PM)

**Comment by fossfreedom** [comment]
yep - good spot - it was bootstrap.min.js missing. cheers

**Comment by fossfreedom** [comment]
fixed in https://github.com/UbuntuBudgie/budgie-welcome/commit/10a5cd976e7c99da8b9c0c630dc8eff89f268499
