### ISSUE TITLE
Is it possible to test it in Debian stretch

### ISSUE THREAD

**Issue by bh-e** [UbuntuBudgie/budgie-welcome#128]
hello,I want to test it in debian stretch . Thus I can run in my new distro that I am creating based on 
Debian . 

I pulled the .deb image from ubuntu zesty repo and installed it in my machine. 

```bhe@machine1$budgie-welcome
Traceback (most recent call last):
  File "/usr/bin/budgie-welcome", line 1535, in <module>
    systemstate = SystemState()
  File "/usr/bin/budgie-welcome", line 874, in __init__
    self.gatherDistroInfo()
  File "/usr/bin/budgie-welcome", line 926, in gatherDistroInfo
    self.official = int(self.os_version[:2]) >= 17
ValueError: invalid literal for int() with base 10: '9.'  ```

**Comment by fossfreedom** [comment]
aye - the code is expecting version numbers to be 2 digits - stretch is obviously just one

just assign self.official = False rather than trying to calculate based on the version of the OS.

**Comment by bh-e** [comment]
@fossfreedom , Thank you , it worked.
