### ISSUE TITLE
Budgie Welcome – Text Spacing Inconsistency

### ISSUE THREAD

**Issue by Schyken** [UbuntuBudgie/budgie-welcome#129]
Going through the Budgie Welcome, under the Introduction section, I noticed that certain areas of text appear to be spaced more than necessary, and after taking another look, I noticed the additional spaces appeared before links. This only seems to occur before links regarding Microsoft Windows, Apple OSX, and Google Chrome OS, and does occur towards the bottom of the document.
![image](https://user-images.githubusercontent.com/20944747/27812820-81761cfe-6026-11e7-9194-3c02aa62ff7b.png)

**Comment by fossfreedom** [comment]
Thanks for raising this @Schyken - much appreciated.
We'll have a closer look in due course - feel free to have a look yourself if you have the time and suggest a pull-request.  Its easier than you may think - there pages are in ./data and are basically simple HTML pages.

cheers
