### ISSUE TITLE
"then the " in drivers section

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#132]
Under the drivers part of the welcome screen, it should say "than the" rather than "then the" ​
![](https://ibin.co/3S9c9pIIP2Gp.jpg)

**Comment by niyasc** [comment]
Can we add some labels like `Byte Sized` in small issues and share in it social media, so that we can attract beginners to contribute?

elementary OS usually tags small issues with `byte sized` label.
