### ISSUE TITLE
Bootstrap 4 upgrade to 4.x

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#149]
We are currently using bootstrap 4 alpha 6.  

4.1.3 is now available.  We should try this and resolve any issues.

~http://getbootstrap.com/docs/4.0/getting-started/download/~
https://getbootstrap.com/

**Comment by ayr-ton** [comment]
How is this going? I would like to help but probably I would need to learn a lit bit more about your development processes.
