### ISSUE TITLE
Add dropbox as a recommendation

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#157]
confusion reigns - some end-users are installing the .deb directly from dropbox and then end up wondering why no working indicator is in the appindicator

This is because  dropbox have hard-coded the appindicator stuff to "Unity".

If users install nautilus-dropbox then this has been patched to correctly display the appindicator.

Lets add this as a recommendation.

**Comment by fossfreedom** [comment]
We are not promoting anything. It's just a recommendation on the best way to install a very popular cross platform solution  on UB.  Too often  people install dropbox via their website and the  complain it doesn't work. Welcome just installs dropbox in a way that works for UB.

**Comment by violoncelloCH** [comment]
Okay, that's probably a matter of opinion...
Would you mind changing "secure" to "popular" if I create a PR for it? I think this would be a more accurate description for dropbox.

**Comment by fossfreedom** [comment]
sure.  that's fine.
