### ISSUE TITLE
[Feature Request] Premade layouts

### ISSUE THREAD

**Issue by ghost** [UbuntuBudgie/budgie-welcome#161]
I think it would be nice to have pre-made layouts available on the welcome app. I think it would compliment theme and applet choosers nicely. Ubuntu MATE seems to do a similar thing and I think it would be good for newcomers to be able to choose a familiar (as in OS X "top panel, global menu and a dock" or Windows "bottom panel" style) layout with one click.

**Comment by fossfreedom** [comment]
This one is similar - this issue raise is much wider though https://github.com/UbuntuBudgie/budgie-welcome/issues/153

Not difficult to implement - just lack of time with higher priority stuff.  Help always welcome!
