### ISSUE TITLE
gettings started keyboard shortcuts need to be extended

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#168]
We have new keyboard shortcuts for 18.04 - we need to describe these in this section of getting started

 - all the .dconf files here https://github.com/UbuntuBudgie/budgie-desktop-environment/tree/master/keycontrol/custom-keys.d

**Comment by manderso7** [comment]
I've added the Alt-Q into "Common application shortcuts" / Toggle tilix quake mode section. Should I find a home for the rest of the sections, or create a new section, maybe "New Gnome shortcuts added in 18.04"?

**Comment by fossfreedom** [comment]
Think they will fit somewhere in the existing sections:

https://github.com/UbuntuBudgie/budgie-welcome/blob/master/data/gettingstarted.html#L1047

Budgie Desktop shortcuts
Common application shortcuts
Desktop shortcuts
Window shortcuts - general
Window shortcuts - numeric keypad (19.04 only)

Don't think "GNOME" means much to people in this area IMHO

**Comment by fossfreedom** [comment]
Added to eoan branch https://github.com/UbuntuBudgie/budgie-welcome/tree/eoan
