### ISSUE TITLE
issue in Getting Started with the pt_BR language - Ubuntu Budgie 18.04

### ISSUE THREAD

**Issue by Lopesgit** [UbuntuBudgie/budgie-welcome#176]
I am having issue with the pt_BR language in the Getting Started options in Ubuntu Budgie 18.04 as attached images.
 
![screenshot from 2018-03-30 19 57 25](https://user-images.githubusercontent.com/1676541/38156495-ada655fc-3454-11e8-9b97-756cd2065e5e.png)
![screenshot from 2018-03-30 19 55 55](https://user-images.githubusercontent.com/1676541/38156497-aeb86e8a-3454-11e8-8f2d-e1a730c89165.png)
![screenshot from 2018-03-30 19 59 20](https://user-images.githubusercontent.com/1676541/38156520-e474f606-3454-11e8-93ce-66f94a7adafb.png)
![screenshot from 2018-03-30 19 49 47](https://user-images.githubusercontent.com/1676541/38156431-38f46848-3454-11e8-960c-7d48170f600d.png)

**Comment by fossfreedom** [comment]
thanks - there was a mistake in the getting started translation.

I have deleted this broken translation.  

When someone re-translates this string via [transifex](https://www.transifex.com/ubuntu-budgie/budgie-welcome) I will upload a new version of budgie-welcome.

**Comment by fossfreedom** [comment]
fixed in the latest snap
