### ISSUE TITLE
budgie welcome does not start at all

### ISSUE THREAD

**Issue by srlopez** [UbuntuBudgie/budgie-welcome#191]
Launching Budgie Welcome from the menu does not start at all.
This happened to me with version 18.04. So I installed the 18.10 in the hope that it would be arrag. But it was not like that.

The problem is that when you click on the Budgie-Welcome menu (or themes, or applets) for a few seconds, the icon appears in the Dock, but disappears and you can not see anything on the screen.

Instalation and removing then package does nothing.
```
$sudo apt install budgie-welcome
...
The following NEW packages will be installed:
  budgie-welcome
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
...
Setting up budgie-welcome (0.6.1) ...
...
$ sudo apt remove budgie-welcome
...
The following packages will be REMOVED:
  budgie-welcome
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
...
Removing budgie-welcome (0.6.1) ...
...
```
But Budgie Welcome remain in the menu.

How can I get a detail of the error that is happening?
I tried to execute the command from the console and I did not get anything clear.

```
santi@metabook:~$ env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/ubuntu-budgie-welcome_budgie-welcome.desktop /snap/bin/ubuntu-budgie-welcome.budgie-welcome %U
```
**snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks**

And with sudo
```
santi@metabook:~$ sudo env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/ubuntu-budgie-welcome_budgie-welcome.desktop /snap/bin/ubuntu-budgie-welcome.budgie-welcome %U
```
**cannot change profile for the next exec call: No such file or directory**
```
But the file is there.
Thanks

**Comment by fossfreedom** [comment]
odd ... very odd

Try the following to force a reinstall:

    sudo apt purge budgie-welcome
    snap remove ubuntu-budgie-welcome
    snap install ubuntu-budgie-welcome --classic

**Comment by fossfreedom** [comment]
sounds like a bug with snapd and/or apparmor - the same snap-confine message was reported here:

https://forum.snapcraft.io/t/snap-confine-has-elevated-permissions-and-is-not-confined-but-should-be-refusing-to-continue-to-avoid-permission-escalation-attacks/5557

Please can you have a look at the topic and try the suggestion.  I presume you are running stock kernel and snapd and not installed from somewhere else.  Might be worth bumping that upstream topic reporting that you have the same issue running classic based snaps.

Are you running a firewall or made any other clampdown/lockdown ?

**Comment by srlopez** [comment]
Nothing new.
```
santi@metabook:~$ snap version
snap    2.35.5+18.10
snapd   2.35.5+18.10
series  16
ubuntu  18.10
kernel  4.18.0-10-generic
santi@metabook:~$ sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/*
santi@metabook:~$ sudo cat /sys/kernel/security/apparmor/profiles
snap.spotify.spotify (enforce)
snap.docker.machine (enforce)
snap-update-ns.spotify (enforce)
snap-update-ns.docker (enforce)
snap-update-ns.core (enforce)
snap.docker.dockerd (enforce)
snap.docker.hook.post-refresh (enforce)
snap.docker.hook.install (enforce)
snap.docker.help (enforce)
snap.docker.compose (enforce)
snap.docker.docker (enforce)
snap.core.hook.configure (enforce)
/snap/core/5662/usr/lib/snapd/snap-confine (enforce)
/snap/core/5662/usr/lib/snapd/snap-confine//mount-namespace-capture-helper (enforce)
snap.ubuntu-budgie-welcome.hook.remove (complain)
snap.ubuntu-budgie-welcome.hook.post-refresh (complain)
snap.ubuntu-budgie-welcome.hook.install (complain)
snap.ubuntu-budgie-welcome.budgie-welcome (complain)
snap.ubuntu-budgie-welcome.budgie-themes (complain)
snap.ubuntu-budgie-welcome.budgie-applets (complain)
snap-update-ns.ubuntu-budgie-welcome (enforce)
docker-default (enforce)
```

All snap ara enforce, but budgie is complain.
Don't know what does mean?

**Comment by srlopez** [comment]
OHMG!
```
santi@metabook:~$ sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
santi@metabook:~$ sudo env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/ubuntu-budgie-welcome_budgie-welcome.desktop /snap/bin/ubuntu-budgie-welcome.budgie-welcome %U
[Notifier] Failed to initialize notifier 
```
And Buggie-Welcome is alive again!!!!
