### ISSUE TITLE
Reset Alignment in Themes

### ISSUE THREAD

**Issue by Thomashighbaugh** [UbuntuBudgie/budgie-welcome#197]
![Alignment Nightmares](https://user-images.githubusercontent.com/32242061/50318712-c852ce00-0477-11e9-8b63-88c8c955c0b5.png)
Be advised the alignment in the themes section is a little caddy whompus. 

I am looking for the exact setting cause, be it a dependency or the site-specific CSS, but wanted to alert you to the issue asap!

**Comment by ShoaibIN** [comment]
I was trying to find the themes section but couldn't find it anywhere. This issue is pretty old so was wondering is it still open? Also I am not able to test live it using the steps on ReadMe on windows. Currently using VSCode with Live Server as alternative.

**Comment by fossfreedom** [comment]
The themes page is data/default.html

As to testing via windows ... sorry I have never run via windows only ubuntu budgie.

I do use vscode on ubuntu budgie!

**Comment by ShoaibIN** [comment]
@fossfreedom Hey, do you mind checking this pull request? It's my first time doing a real pull request so let me know if I did something wrong

**Comment by fossfreedom** [comment]
Thx. When I am next at my computer I will review. Cheers.
