### ISSUE TITLE
Responsiveness at Full Screen 

### ISSUE THREAD

**Issue by Thomashighbaugh** [UbuntuBudgie/budgie-welcome#198]
On the Home Page at Full Screen the logo/buttons/etc all remain above the middle of the screen. Considering the media queries are all well adjusted, and assuming we aren't dogmatic about the above-the-fold rule at the expense of the design, it would look better to have some sort of CSS adjustment for maximized screens of a specific size to then drop the components down and improve the appearance of the app overall. 

Screen Size: 1600x900

**Comment by ShoaibIN** [comment]
so I was looking around the index.html code and found this
`<img id="wordmark" src="img/welcome/blank.svg">`
Problem is that there is no blank.svg file in welcome folder. There is blank-wordmark though but it is blank like it's name, The Main page of Budgie Welcome is index.html right?

**Comment by fossfreedom** [comment]
Correct index.html. hmm not sure about why the file is not there. Sounds
like a mistake ... or it got lost at some point.

**Comment by ShoaibIN** [comment]
#244
