### ISSUE TITLE
stop uninstalling showtime, Quicknote and Dropby

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#206]
We should prevent the above to applets being uninstalled via welcome - we now know that resetting the panel causes panel icons to wander around.  

This is due to the panel.ini we have that gives us our default layout.  Due to a bug in budgie-desktop, when applets are missing from the panel.ini layout, it can't cope with positioning applets correctly.

**Comment by Jacob-Vlijm** [comment]
That means removing them from Welcome? But what about the other ones, they can also be removed while on the panel...
