### ISSUE TITLE
Themes should be in alphabetical order

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#210]
Themes are shown on the default settings page in a non alphabetical order which is not intuitive

**Comment by HellBringer419** [comment]
This seems easy.
There are two solutions to this:
1. Change the order manually in the [default.html](https://github.com/UbuntuBudgie/budgie-welcome/blob/master/data/default.html) file. (static approach)
2. Tell JS to arrange them in alphabetical order based on the theme's name. An additional function would be required to do this. And all the present themes should be added to an array or List and accordingly updated when required. (dynamic approach)

Please tell me your thoughts on this and I would do the required changes.

**Comment by fossfreedom** [comment]
Hi and thx

Static approach is a pain because pages are generated for each translation and as such are overwritten each time a regen is performed.

So a more dynamic approach is required along the lines of the javascript used for sorting 
budgie applets line 474 of welcome.js invoked from the budgie applets page

**Comment by HellBringer419** [comment]
Okay, I got it. 
here's the snippet:
` function sortThemes() {`
` $('#themes').append($('#themes > div > div').sort(function (itemOne, itemTwo) {`
` var titleOne = $(itemOne).find('h3').text();`
` var titleTwo = $(itemTwo).find('h3').text();`
` return titleOne.localeCompare(titleTwo);`
` }));`
` }`

This should be called on onLoad() of the body of default.html. The function is to written just after the sortAppletList() in welcome.js file.

Also, I'm issuing a pull request to provide this modification.

**Comment by HellBringer419** [comment]
Added a pull request resolving the issue.
Commit e43690789872b039b432d991cac654ea88e76d0d.

Please verify and if correct, close the issue.

**Comment by HellBringer419** [comment]
Happy to help 😊
