### ISSUE TITLE
Budgie-Welcome getting started

### ISSUE THREAD

**Issue by manderso7** [UbuntuBudgie/budgie-welcome#222]
If I click the "Features" or "Introduction" links in Budgie Welcome, I'm able to go back to the Budgie Welcome main screen by clicking the back arrow at the top of the window. However, when I click the back arrow in the "Getting Started" section, the ?side menu? opens, to do various things like choose a browser or customize something. Going back to the main Welcome window doesn't happen at all, and there doesn't seem to be a way to go back. 
![Screenshot from 2019-05-16 05-32-13](https://user-images.githubusercontent.com/9535390/57843307-ff65ab00-779b-11e9-81b3-12b252a4b974.png)

**Comment by manderso7** [comment]
I see more of what's going on.
If you click the "x" at the top of the side menu, the side menu goes away for whatever reason and you're left with the "Please choose a topic" text. Clicking the back arrow brings back the menu. Clicking the back arrow again takes you back to the main menu. For some reason, that didn't happen for me when I had the budgie welcome program open at one point, but closing and re-opening the program allows me to go back to the Welcome screen now.
I can close this if you like, however, the X for the menu is misleading and I think it should be removed.

**Comment by fossfreedom** [comment]
Just clicking the left arrow again goes backwards

**Comment by fossfreedom** [comment]
good point about the x - yeah agree.  needs to be removed.

**Comment by manderso7** [comment]
It's not just the X though. If you click outside the menu in that window, the menu goes away, leaving just the "Please choose a topic" text. Clicking the arrow brings the menu back.

**Comment by fossfreedom** [comment]
hmm - yeah - the logic needs to be better to keep the menu open if you haven't first selected a topic.

**Comment by fossfreedom** [comment]
fixed in v0.8.5 which will appear in the next few days or you can force a download via

    snap refresh
