### ISSUE TITLE
Links to social media go no where

### ISSUE THREAD

**Issue by manderso7** [UbuntuBudgie/budgie-welcome#223]
![Screenshot from 2019-05-16 05-51-32](https://user-images.githubusercontent.com/9535390/57844748-af3c1800-779e-11e9-870a-9c20139ef08c.png)
Mousing over the buttons/links gives the text showing the name of the site, but not the url. Clicking the buttons does nothing, doesn't open a browser window.

**Comment by fossfreedom** [comment]
odd. Works here - what version of UB have you installed?

    xdg-open https://ubuntubudgie.org

Does the above copied and pasted into a terminal open the browser to our home-page?

**Comment by manderso7** [comment]
It does open the browser to the home page. 
manderso@boop:/usr$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by fossfreedom** [comment]
Full UB install?

**Comment by manderso7** [comment]
Yeah, I don't recall making any changes during the install. It's been a minute though.

**Comment by fossfreedom** [comment]
Please run 

    budgie-welcome

Then hover over the icon and click the popup

Any messages reported in the terminal?

**Comment by manderso7** [comment]
No messages reported in the terminal on hover or clicking of icons.

**Comment by fossfreedom** [comment]
Nothing when clicking on the hover popups?

**Comment by manderso7** [comment]
That works just fine. I had no idea those were clickable. You can close this, my apologies.
