### ISSUE TITLE
Suggestion - Appearance settings changes

### ISSUE THREAD

**Issue by manderso7** [UbuntuBudgie/budgie-welcome#226]
The Switch Appearance page allows one to change to a different budgie theme. It may help to add a link to the Budgie Desktop Settings program on that page, perhaps in the "Switch Appearance" line.
Also, is there a way to add more budgie themes to this page? I haven't seen how, if so. If there is a way, perhaps mention that here as well.

**Comment by manderso7** [comment]
Hell, this isn't in the right repo. Sorry, closing.

**Comment by fossfreedom** [comment]
Not possible with v10.5 of budgie desktop. But should be possible in v11 and later where is is promised by upstream to make settings more flexible.

As to the themes, yes it is possible to add more if those themes icons and cursors are available as deb packages either in the ubuntu repositories or in a recognised and reliable PPA.  Such themes need to be added to the themes html file and related data folder files in budgie welcome itself.
