### ISSUE TITLE
Error launching budgie-welcome - XAUTHORITY & ubuntu-budgie-welcome/182: Not a directory

### ISSUE THREAD

**Issue by srlopez** [UbuntuBudgie/budgie-welcome#245]
Lauching Budgie Welcome, Themes, etc... from the desktop menu doesn do anything.
So i tray to launch from the commandline with `$ budgie-welcome` and this is the result:

```
$ budgie-welcome 
2020/04/03 13:16:23.612424 cmd_run.go:529: WARNING: XAUTHORITY environment value is not a clean path: "/mnt/hdd2/santi/.Xauthority"
cannot create user data directory: /home/santi/snap/ubuntu-budgie-welcome/182: Not a directory
```
But **it works** sudoing the command, with some warnings:
```
$ sudo budgie-welcome 
2020/04/03 13:17:25.474082 cmd_run.go:529: WARNING: XAUTHORITY environment value is not a clean path: "/mnt/hdd2/santi/.Xauthority"
[Notifier] Failed to initialize notifier 

(WebKitWebProcess:10303): Gtk-WARNING **: 13:17:26.395: Theme parsing error: gtk.css:6078:9: 'bordert' is not a valid property name
```
The problem looks something related to the snap directory, wich exits.
My environment is:,
```
$ uname -a
Linux slimbook 5.4.22-050422-generic #202002240833 SMP Mon Feb 24 08:35:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ env | grep XAUT
XAUTHORITY=/home/santi/.Xauthority
```
I have my home directory linked to a second drive. 
```
$ cd /home 
santi@slimbook:/home$ ll
total 8
drwxr-xr-x  2 root root 4096 feb 28 13:43 ./
drwxr-xr-x 24 root root 4096 abr  1 17:14 ../
lrwxrwxrwx  1 root root   15 feb 28 13:43 santi -> /mnt/hdd2/santi/
```
What can i do?

**Comment by fossfreedom** [comment]
As far as I can gather looking at the snapcraft.io forum you cannot have a home folder symlinked to a second drive - the snap folder and home folder has to reside on the main drive.

This is the relevant issue that you should read.  There isnt anything that we can do - it apparently is by design

**Comment by fossfreedom** [comment]
apologies - forgot the link https://bugs.launchpad.net/snappy/+bug/1620771
