### ISSUE TITLE
Missing a space

### ISSUE THREAD

**Issue by murraybd** [UbuntuBudgie/budgie-welcome#258]
https://github.com/UbuntuBudgie/budgie-welcome/blob/45102aa7b8f46a7d2a8d0f1ba74bb51e7ca7a18c/data/gettingstarted.html#L443

There's no space between "Ubuntu" and "(the base distribution".

**Comment by fossfreedom** [comment]
Closing via PR https://github.com/UbuntuBudgie/budgie-welcome/pull/259
