### ISSUE TITLE
Empty screen ubuntu-budgie-welcome.budgie-themes  and ubuntu-budgie-welcome.budgie-themes -v -d -locale=es_ES

### ISSUE THREAD

**Issue by srlopez** [UbuntuBudgie/budgie-welcome#261]
Running `budgie-welcome -v -d --locale=es_ES.UTF-8` or `ubuntu-budgie-welcome.budgie-themes -v -d -locale=es_ES` just show an empty screen..

![see the image here](https://i.imgur.com/PcsY8OJ.jpg)
```bash
santi@slimbook:~$ budgie-welcome -v -d --locale=es_ES.UTF-8
[Debug] Verbose mode enabled. 
[Debug] Running in debugging mode. 
[Debug] Setting locale to: es_ES.UTF-8 
[Welcome] Using /snap/ubuntu-budgie-welcome/245/usr/share/budgie-welcome/ path. 
[Welcome] Using /snap/ubuntu-budgie-welcome/245/usr/share/budgie-welcome/ path. 
[i18n] Locale Not Available: es_ES.UTF-8 (using en_US instead) 
[Welcome] Using /snap/ubuntu-budgie-welcome/245/usr/share/budgie-welcome/ path. 
[i18n] Locale Set: es (using relative path) 
[i18n] Page Verified: budgie-applets.html 
[i18n] Page Verified: community.html 
[i18n] Page Verified: default.html 
[i18n] Page Verified: donate.html 
[i18n] Page Verified: features.html 
[i18n] Page Verified: getinvolved.html 
[i18n] Page Verified: gettingstarted.html 
[i18n] Page Verified: index.html 
[i18n] Page Verified: introduction.html 
[i18n] Page Verified: recommendations.html 
[i18n] Page Verified: store.html 
[i18n] All translated i18n pages found. 
[i18n] res_dir: ../../ 
[i18n] Using locale for gettext: es 
[i18n] Using path for gettext: /snap/ubuntu-budgie-welcome/245/usr/share/budgie-welcome/../locale/ 
[i18n] Translation found for gettext. 
[Specs] Detecting graphics vendor...  
[Network Test] Establishing a connection test to "http://archive.ubuntu.com/" 
[Welcome] Using /snap/ubuntu-budgie-welcome/245/usr/share/budgie-welcome/ path. 
[i18n] Locale Set: es (using relative path) 
[Welcome] Successfully pinged: http://archive.ubuntu.com/ 
[Specs] Detected: Intel Corporation UHD Graphics (rev 02) 
```
and after pressing the status button ...
```bash
Traceback (most recent call last):
  File "/snap/ubuntu-budgie-welcome/245/usr/bin/budgie-welcome", line 1893, in _show_status
    self.webkit._do_command("status")
  File "/snap/ubuntu-budgie-welcome/245/usr/bin/budgie-welcome", line 698, in _do_command
    message, PopupMessage.STATUS, pm.getTaskList())
  File "/snap/ubuntu-budgie-welcome/245/usr/bin/budgie-welcome", line 1099, in getTaskList
    taskList = [["INSTALL" if self.active.task ==
AttributeError: 'NoneType' object has no attribute 'task'
```
And the same with  ubuntu-budgie-welcome.budgie-themes -v -d`
Tested with the --locale set to es_ES, es_ES.UTF-8, en_US, en_US.UTF-8, etc..
```
santi@slimbook:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
santi@slimbook:~$ uname -a
Linux slimbook 5.5.14-050514-lowlatency #202004011032 SMP PREEMPT Wed Apr 1 10:39:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I've tray the following commands
```
sudo snap refresh
sudo snap remove ubuntu-budgie-welcome 
sudo snap install ubuntu-budgie-welcome --classic
```
but nothing has changed.
Thanks in avance.

**Comment by fossfreedom** [comment]
![image](https://user-images.githubusercontent.com/996240/102256870-d8d19e00-3f03-11eb-8707-b9e0b282f26d.png)

Running `budgie-welcome -v -d --locale=es_ES.UTF-8` shows this for me.

So I'm not really sure what is going wrong on your hardware.

**Comment by srlopez** [comment]
Nothing new.
Same result

**Comment by fossfreedom** [comment]
please boot into a live USB session and look at budgie-welcome - that will check if this is due to a recent webkit update /  graphics update in 20.04.1

**Comment by srlopez** [comment]
I do not think so.
After the first installation in March (more or less) there was no problem.
It is now after several months without using it that I have realized that it does not work.
I have tested it with the Intel and NViDIA driver. Both wrong.

**Comment by srlopez** [comment]
> ![image](https://user-images.githubusercontent.com/996240/102256870-d8d19e00-3f03-11eb-8707-b9e0b282f26d.png)
> 
> Running `budgie-welcome -v -d --locale=es_ES.UTF-8` shows this for me.
> 
> So I'm not really sure what is going wrong on your hardware.

**Comment by fossfreedom** [comment]
try purging the snap data - maybe something is cached wrongly:

    snap remove --purge ubuntu-budgie-welcome
    snap install ubuntu-budgie-welcome --classic

**Comment by srlopez** [comment]
Same result.
Empty window
![here](https://i.imgur.com/2bGfBUQ.jpg)

**Comment by fossfreedom** [comment]
Just wondering if this is local to your account - or system wide.

Suggest create a new user account and login - see if budgie-welcome
displays correctly or not.

**Comment by srlopez** [comment]
:open_mouth:
You point in the right direction
`sudo budgie-welcome` has done the magic
![ohmg!!!!](https://i.imgur.com/Cp7kJeP.jpg)
So it seems permission issue.
How do I fix it for the normal user?
We are close

**Comment by fossfreedom** [comment]
not sure really.

you have in your own account a .snap folder

You also have a snap folder

Finally budgie welcome writes to ~/.config/budgie-welcome

So you could remove that ~/.config/budgie-welcome folder first then launch budgie-welcome

Double check the permissions of the .config folder itself

Similarly check the permissions on .snap

**Comment by srlopez** [comment]
SOLVED.
Your information point in the right direction
Premision on ~/cache/budgie-welcome/
```
sudo rm -rf .cache/budgie-welcome/
```
And everythink is OK
Thanks.
