### ISSUE TITLE
 Budgie welcome There are some garbled codes in non-English speaking countries

### ISSUE THREAD

**Issue by eremiter** [UbuntuBudgie/budgie-welcome#296]
[https://global.discourse-cdn.com/standard17/uploads/ubuntubudgie/optimized/2X/0/07cc0ae3928e86a53edba711ec3b275c295ce340_2_690x380.png](url)
` <span class="btn-icon material-icons">&#xE88E;</span>`
I found a solution, which is that these address symbols, if you change them to words, you don’t have a garbled code.

Please fix it, thank you

**Comment by eremiter** [comment]
Hello Sir,
Use this so you don't mess up the code.

Best regards,
 
From: David Mohammed
Date: 2022-11-11 22:59
To: UbuntuBudgie/budgie-welcome
CC: Budgie; Author
Subject: Re: [UbuntuBudgie/budgie-welcome] Budgie welcome There are some garbled codes in non-English speaking countries (Issue #296)
No. That will force translations.
We need to find a better way to display the symbols forcing a font rather than using the system font

**Comment by fossfreedom** [comment]
https://github.com/UbuntuBudgie/budgie-welcome/commit/b48a2ffb8044cc0068118d98b0689d80b9a66c2b

Should now be resolved with the snap in the edge channel
