### ISSUE TITLE
Improve panel transparency for Material Design theme

### ISSUE THREAD

**Issue by Udara-U3** [UbuntuBudgie/budgie-welcome#42]
![virtualbox_budgie 16 10_18_10_2016_16_01_33](https://cloud.githubusercontent.com/assets/12265797/19477548/c485bbd2-954f-11e6-85a7-2c13b7ab33c8.png)

After switched to Material Design using Welcome app, **Budgie panel is almost fully transparent.**
Currently Transparent amount is `0.1`, I think least `0.3` would be better.

![virtualbox_budgie 16 10_18_10_2016_16_30_40](https://cloud.githubusercontent.com/assets/12265797/19477648/3a6e2d98-9550-11e6-8272-e86bae4e7be8.png)

And when Panel is Transparent, **Turning off Panel shadow** will make it better.

**Comment by niyasc** [comment]
Panel transparency is changed to 0.3. At the moment it is difficult to change the shadow, as it is a property associated with individual panels.

Upstream is looking for a global settings to alter shadow behavior. https://github.com/budgie-desktop/budgie-desktop/issues/480
