### ISSUE TITLE
multiple panels on undo

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#46]
https://bugs.launchpad.net/budgie-remix/+bug/1636800

ProblemType: Bug
DistroRelease:Budgie remix 16.10
Package: Budgie v10.2.8
Uname: Linux 4.8.0-26-generic
Architecture: 64 bit

When using the Budgie Welcome->Default Settings->Restore panels->Reset Budgie panel and then undo reset it will multiply the panel/s every time.
The single way to fix this is to restart the system.

Screenshots as per the bug report

**Comment by niyasc** [comment]
Strange? Is it something associated with new budgie release?

**Comment by fossfreedom** [comment]
not sure @niyasc - I haven't looked at the code ... but for the undo routine I presume we clear the old "file" before we save the new panel values before doing the reset?

**Comment by ikeydoherty** [comment]
Doing the dconf reset is hazardous as it messes with the currently running panel managers internal state. This is why the latest git version of Budgie has a new "--reset --replace&" option. I am going to go one further though, and have a single key to define the default panel layout, and allow the shipment of multiple panel layouts within Budgie Desktop, which will help resolve this issue.

**Comment by fossfreedom** [comment]
The new budgie-panel --reset method in yakkety and later is broken due to the later glib version.

Going to have to code around this - use the reset method for 16.04 and a dconf method for 16.10 and later

**Comment by niyasc** [comment]
But the initial approach (dconf reset) was causing the problem of having multiple panels. Right?

**Comment by fossfreedom** [comment]
yeah. i will need to investigate this ... possibly disable the undo functionality to yakkety and later

On 14 Jan 2017 05:01, Niyas C <notifications@github.com> wrote:

But the initial approach (dconf reset) was causing the problem of having multiple panels. Right?

**Comment by fossfreedom** [comment]
k - have removed the undo - it is causing too many issues with applets being duplicated on panels and flicking around.

Put pack in the dconf reset method for 16.10 and later.
