### ISSUE TITLE
Recommendations page should be sorted

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#48]
If possible with a bit of JavaScript - we should sort the div sections so that those recommendations already installed should appear at the bottom of the page. Those options not installed should be at the top.

Reference: https://stackoverflow.com/questions/34913953/move-an-element-one-place-up-or-down-in-the-dom-tree-with-javascript

**Comment by niyasc** [comment]
We are querying installation status in python script. So, we will have to perform DOM manipulation through webkit `run_javascript` method as we do toggling between **install/remove** buttons.

So my idea is to keep recommendations in a separate `.json` file and load them dynamically after sorting primary with respect to installation status and secondly with respect to alphabetical order(or something else)

Any thoughts?

**Comment by fossfreedom** [comment]
Actually that is a very nice out-of-the-box thinking.  I like that idea.

**Comment by niyasc** [comment]
Ok. I will work on it over weekend.

**Comment by niyasc** [comment]
This issue is addressed by https://github.com/UbuntuBudgie/budgie-welcome/commit/07478546cc58891e0c967e7607a742a5f590f332.
