### ISSUE TITLE
Use alternate Material Design theme upon detecting low-res screen

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#49]
Currently, we use `Adapta` theme when Material Design mode is selected. We should also calculate the screen resolution; for lower resolution screens we should be using `Adapta-Eta` or `Adapta-Nokto-Eta` instead of Adapta (all available under the [same repo](https://launchpad.net/~tista/+archive/ubuntu/adapta) in the same `adapta-gtk-theme` package).

**Comment by fossfreedom** [comment]
more info from Tista

Just my thoughts, FHD (1080p) already became LOW resolution today. And Adapta is scaling Gtk+ theme, it means spacing depends on your font-size and font-scaling-factor. In Material Design, 13px(9.75pt) or 14px(10.5pt) are recommended as standard widget font-size in case if your -gtk-dpi was set to 96. So Adapta uses 13.33px (10pt) as nominal font-size for px-to-rem conversion.

It means 12pt or 13pt font-family are completely unmatch with my theme (I don't have any ideas when we need such large fonts as widget standard).

EDIT

I forgot to mention.
Eta variants are available in Gtk+ 3.2x only (Gtk+ 3.18.x theming does not use rem but em).

**Comment by Udara-U3** [comment]
@fossfreedom I think we can go with `Adapta-Eta` the reason is, without it it will be missing some configuration buttons in Raven. Check [this](https://github.com/adapta-project/adapta-gtk-theme/issues/222) issue which I have reported earlier. I have fixed this issue and font problems using `Adapta-Eta`

**Comment by fossfreedom** [comment]
agreed @Udara-U3 - though from Tista's description above we can only choose Adapta-Eta for Yakkety and later since its not available for Xenial users.

**Comment by HEXcube** [comment]
Tested both **Adapta** and **Adapta Eta** under my non-HD notebook. See results:

- **Adapta**:
![adapta](https://cloud.githubusercontent.com/assets/3755396/19838258/3be7a726-9ef1-11e6-8e70-dd08f67a47b8.png)

- **Adapta Eta**:
![adapta eta](https://cloud.githubusercontent.com/assets/3755396/19838260/40a2b3be-9ef1-11e6-9582-74f2d50b26ee.png)

@Udara-U3 and @fossfreedom Like u guys pointed out, the Eta variant with its reduced padding and space saving, is definitely better on non-HD screens. However, on my work machine with HD screen, regular Adapta looks better. And I believe it'll look better on HiDPi screens too.

**Comment by fossfreedom** [comment]
What's the resolution of you had screen that looks better with adaptation and what's the resolution that works better with ETA?  Did you change the font sizes as vista recommended?

On 30 Oct 2016 17:11, HEXcube <notifications@github.com> wrote:

Tested both Adapta and Adapta Eta under my non-HD notebook. See results:

  *   Adapta:
[adapta]<https://cloud.githubusercontent.com/assets/3755396/19838258/3be7a726-9ef1-11e6-8e70-dd08f67a47b8.png>

  *   Adapta Eta:
[adapta eta]<https://cloud.githubusercontent.com/assets/3755396/19838260/40a2b3be-9ef1-11e6-9582-74f2d50b26ee.png>

@Udara-U3<https://github.com/Udara-U3> and @fossfreedom<https://github.com/fossfreedom> Like u guys pointed out, the Eta variant with its reduced padding and space saving, is definitely better on non-HD screens. However, on my work machine with HD screen, regular Adapta looks better. And I believe it'll look better on HiDPi screens too.

**Comment by HEXcube** [comment]
> What's the resolution of you had screen that looks better with Adapta and what's the resolution that works better with ETA?

@fossfreedom My home notebook's 1366x768 size. Work machine's 1600x900 (okay not Full HD, but still close). Gotta test on my colleagues' HiDPi displays too.


> Did you change the font sizes as Tista recommended?

No, didn't change any font setting. Just kept the default fonts.
