### ISSUE TITLE
add a switch to the language screen

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#53]
ok - for the language screen we should add a big button to allow the user to switch to their keyboard entry of choice - IBUS (it is the default currently) to FCITX

This button needs to install the fcitx package

To switch to FCITX run "im-config -n fcitx"

**Comment by fossfreedom** [comment]
ok - more on this - the language screen I seem to remember installs IBUS packages

So this is a bit more involved - if the user has chosen "FCITX" then it should deinstall the IBUS packages and install the FCITX packages

http://packages.ubuntu.com/search?keywords=fcitx&searchon=names&suite=yakkety&section=all

**Comment by niyasc** [comment]
Let me confirm my understanding on this

- There will be two buttons for one for iBus & fcitx. Either of the button will be disabled at a time, depending on the package installed.
- When we select button corresponding to iBus
  - Package named `ibus` will be installed
  - Package named `fcitx` will be removed
  - Command `im-config -n ibus` will be executed

Similarly, for fcitx also. Is it the expected work flow?

**Comment by fossfreedom** [comment]
Exactly that. Spot on. To be honest. Removing the package fcitx is not really needed since the key part is the im-config bit to switch between the two

**Comment by niyasc** [comment]
This issue has been addressed by this commit.
https://github.com/UbuntuBudgie/budgie-welcome/commit/c19acc9f21b87d251b8b9764a4bce120a6e7094a
