### ISSUE TITLE
Material Desktop - UI Improvements 

### ISSUE THREAD

**Issue by Udara-U3** [UbuntuBudgie/budgie-welcome#54]
![virtualbox_zesty_07_11_2016_17_06_47](https://cloud.githubusercontent.com/assets/12265797/20059014/6beb0c48-a50d-11e6-949e-182eb19e72b5.png)

- Budgie Panel shadow has to be turned off for better UI look & feel
- Panel height is better with `32px`

![virtualbox_zesty_07_11_2016_17_09_50](https://cloud.githubusercontent.com/assets/12265797/20059041/8e597c2e-a50d-11e6-9801-401394549a2e.png)

- With Material Design, only Budgie Panel dark mood doesn't do the job, Able get better look by enabling Gnome Global dark mood by `gnome-tweak-tool` we can use `dconf `settings to do this job.

![virtualbox_zesty_07_11_2016_17_11_29](https://cloud.githubusercontent.com/assets/12265797/20059074/c4f421a8-a50d-11e6-88c8-79b077a974db.png)

**Comment by fossfreedom** [comment]
global dark theme is enabled via creating this file (or amending it if it already exists) and contents

```
~/.config/gtk-3.0$ more settings.ini 
[Settings]
gtk-application-prefer-dark-theme=1
```

turning off dark-theme changes gtk-application-prefer-dark-theme=0

shadow and panel size is a bit more complicated - it is on a per panel basis so more difficult to-do via gsettings - probably the keybindings code could be looked at on how to find stuff in relocatable schemas under com.solus-project.budgie-panel.panels
