### ISSUE TITLE
Rename brand

### ISSUE THREAD

**Issue by niyasc** [UbuntuBudgie/budgie-welcome#55]
Rename all references to **budgie-remix** with **Ubuntu Budgie**

**Comment by fossfreedom** [comment]
we need something here to cope with 16.04/16.10 distro - we cannot call these Ubuntu Budgie - nor have budgie-welcome refer these as Ubuntu Budgie.

Weblinks etc are fine though - just the visual text cannot change.

**Comment by HEXcube** [comment]
Maybe split into two or more branches? Separate branch for budgie-remix (16.04) and Ubuntu Budgie (17.04+). Not sure if a 16.10 branch would be needed, coz it's lifespan is short anyway.

**Comment by fossfreedom** [comment]
![workspace 1_008](https://cloud.githubusercontent.com/assets/996240/20467327/3c227e72-af7d-11e6-9cc0-18c256ec03af.jpg)

**Comment by fossfreedom** [comment]
> Maybe split into two or more branches? Separate branch for budgie-remix (16.04) and Ubuntu Budgie (17.04+). Not sure if a 16.10 branch would be needed, coz it's lifespan is short anyway.

no need @HEXcube :)  ^^^ code now renames itself depending on which distro version its running on.

**Comment by HEXcube** [comment]
@fossfreedom Even better! :smile:
