### ISSUE TITLE
install arc-firefox-theme via budgie-welcome

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#59]
Currently we use a debian package called arc-firefox-theme to theme firefox.

Its going to be difficult to coordinate updating this package with the firefox update itself.

Would like to introduce a firefox theming option in budgie-welcome as part of the getting started - or maybe the new browser ballot screen. 

Introduce an option in budgie-welcome that opens the arc-firefox-theme addons webpage. If there was a way to download and autoinstall even better.

Edit: http://askubuntu.com/questions/73474/how-to-install-firefox-addon-from-command-line-in-scripts

**Comment by GrindamN** [comment]
Sure. However in my experience the links tend to be weird when using Arc Darker in Firefox due to blue colors overlapping.

**Comment by fossfreedom** [comment]
no longer interested in getting this into budgie-welcome.  closing.
