### ISSUE TITLE
Desired features

### ISSUE THREAD

**Issue by niyasc** [UbuntuBudgie/budgie-welcome#6]
This is a `TODO` list of features which needs to be implemented after releasing first preview(App in budgie-remix 16.04.1)
1.  Option to switch between _default_ themes `Arc` and `Vertex`. --> DM: kind of duplicates Raven.  We've talked about Arc vs Material i.e. wholesale change (default wallpaper/theme/font/lock screen/greeter screen/plymouth) - if we aim for this, this would be better.
2. Installation queue. Currently, if we click on install/remove button when another installation/removal is in progress, it will show a well formatted error message saying `another installation/removal is in progress and apt was unable to get lock.`. Instead of this, we should maintain a queue and each request to install/remove software should be added to this queue.
3. Translation support.
4.  Modification to work on low resolution screen. Currently app width is `992px`. What to do if screen resolution is below that? --> DM: haven't looks at the webkit API - but should be able to scale/zoom the web-pages if the screen res is lower.

**Comment by niyasc** [comment]
Implementation status.
--------------
1. TODO
2. DONE
3. TODO
4. TODO

**Comment by fossfreedom** [comment]
Wonder if the translate button described here could be useful http://www.nelsonpires.com/web-development/easily-add-translation-capabilities-to-your-website/

Maybe see if the button appears where the locale being used is not English

**Comment by fossfreedom** [comment]
translation support added.  closed
