### ISSUE TITLE
install time for material theme

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#60]
more of a query - when we add the two PPAs for the material theme - are we doing this:

add adapta ppa
update
install package
add paper ppa
update
install package ?

or the more streamlined

add adapta ppa
add paper ppa
update
install paper , adapta packages

i.e. one less update which will greatly improve the install time.

**Comment by niyasc** [comment]
In *privileged actions script*, you can see the script for adding PPA.

    def add_repos(repos):

    if not repos: return 0  
    
    sp = SoftwareProperties()
    for repo in repos:
        # check if its a component that should be added/removed
        distro = aptsources.distro.get_distro()
        distro.get_sources(sp.sourceslist)
        components = [comp.name for comp in distro.source_template.components]
        if repo in components:
            if line not in distro.enabled_comps:
                distro.enable_component(line)
        else:
            sp.add_source_from_shortcut(shortcut_handler(repo))
    sp.sourceslist.save()
    
    # Update always. Ideally, this should be done only if a new repo is added
    # to list
    p = subprocess.Popen(['apt', 'update'])
    
    return p.wait()

As it is evident from the code, `apt update` command is only used once. As mentioned in code comment, one possible issue here is, `apt update` command is executed always, without considering whether repository was already there or not.

**Comment by fossfreedom** [comment]
ok - happy with that.  cheers
