### ISSUE TITLE
Make getting started the default on first run

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#64]
On first run on the desktop ... Not on the lived CD ... Let's make the getting started screen the default opening screen.  Next time the app is run the default current front page will open.

This will make it more obvious for users to set up the desktop immediately after installation.

**Comment by niyasc** [comment]
The main concern here is recognizing whether it is first time or not. Issue #52 is also associated with the same. Any idea on how, gnome is loading `yelp` on first run?

**Comment by fossfreedom** [comment]
no idea about yelp - although this commit is exactly the same for stuff I've done in the past with rhythmbox plugins https://mail.gnome.org/archives/commits-list/2015-July/msg02979.html

basically we test if a folder & file exists in a local .config folder - if not - create the folder and file


```
e.g. (pseudo code) test ~/.config/budgie-welcome/first_run
if exists - first page = index.html
else { 
  create folder ~/.config/budgie-welcome
  create file ~/.config/budgie-welcome/first_run 
  first page = getting_started.html
}
```

**Comment by niyasc** [comment]
Ok. I will try this.
