### ISSUE TITLE
Ubuntu Budgie Brasil on Telegram

### ISSUE THREAD

**Issue by topx84** [UbuntuBudgie/budgie-welcome#65]
We would like to collaborate with the Brazilian user community Ubuntu Budgie, providing support to users through the Telegram app.

Please add in **budgie-welcom - telegram.me/UbuntuBudgie**
Thank you David Mohammed and staff.

_regards,
Tiago Procópio
Email tiagooprocopio@gmail.com
Telegram t.me/topx84_

**Comment by niyasc** [comment]
DONE. 

Though launching a telegram channel requires telegram client installed in system/browser.

![community](https://cloud.githubusercontent.com/assets/2451833/21739844/1f15814c-d4cd-11e6-9286-b515f5d41743.png)

**Comment by topx84** [comment]
Thank you brother.
