### ISSUE TITLE
Freezing on latest zesty build

### ISSUE THREAD

**Issue by GrindamN** [UbuntuBudgie/budgie-welcome#66]
When launched, if you want to install latest zesty version, and you click install now, from welcome app, the app offers dialog. If you choose yes, the application should close, but it stays there frozen along with dialog, which however opens installation.

![bug](https://cloud.githubusercontent.com/assets/9149076/21732427/ba76b1fc-d459-11e6-8feb-9121fb43cffe.jpg)

**Comment by niyasc** [comment]
Can you please launch the app via command line and report the output you see while following same sequence of operations? (if any)

**Comment by fossfreedom** [comment]
@GrindamN I havent seen this freeze issue.  Please update your daily and retry.

**Comment by fossfreedom** [comment]
removed the popup message.  Will upload in a couple of weeks to zesty

**Comment by fossfreedom** [comment]
latest budgie-welcome has been loaded into the repos.  Please update your daily build and retest.

**Comment by fossfreedom** [comment]
presumed closed
