### ISSUE TITLE
Welcome App with Gtk3, Python & Glade - Discussion

### ISSUE THREAD

**Issue by niyasc** [UbuntuBudgie/budgie-welcome#70]
Just came to know about **manjaro-hello**, new Welcome App for Manjaro. It is developed using Gtk3, Python & Glade. Following are their reasons for migrating from webkit based App.

- First, it is based on Gtk3 but because of the use of Webkit and its old Python binding, it is forced to use Gtk2.
- All content of the app is displayed with HTML that is rendered by Webkit. This makes the evolution of the software very complicated. For example, it is very hard to make a translation system.
- By using web technologies and Webkit, the renderer is a little bit slower than using native technologies.
- Can't know if each link will be open in an external browser or in app.

Creating this thread to discuss, whether we need to migrate to a pure Gtk3 implementation.

#### Related links

- [manjaro-hello repository](https://github.com/manjaro/manjaro-hello)
- [Discussions on manjaro-hello](https://forum.manjaro.org/t/start-work-on-a-new-welcome-screen-manjaro-hello/13685/10)

**Comment by fossfreedom** [comment]
pro's - GTK3 + Python very fast,
  fairly lightweight
  simplifies the skill level to make changes - you dont need to know CSS, html javascript
  would look and feel like a native GTK3 app
  agree - would support a native translation system.  I have my doubts though - the amount of text we have would be substantial work for translators.  A web based google translate option maybe the quickest to get a fully translated system.

Con's.
  yes - use of webkit forces GTK2 - however we use webkit2 and later - thus is already GTK3
  It is slower to develop a GUI - GTK3 native text flow, headings, graphics placement is not as dynamic as HTML/CSS - much longer to achieve similar results

Yes - GTK3 links will open in a separate browser window - you'll find it very difficult to "integrate" a web-window in GTK3 - no extra work to make the link open in a browser window.
