### ISSUE TITLE
new IRC channel #ubuntu-budgie

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#73]
on freenode we now have an official IRC channel.

We should add an icon to our contact options with a link to the channel.

As many people may not fully understand IRC - we should clarify:

"If you disconnect from the channel you will not receive a notification of any reply.  So either leave an IRC session open - or we recommend connecting to all ubuntu IRC channels via an IRC bouncer"

**Comment by niyasc** [comment]
- Ubuntu MATE has a direct [IRC link](https://ubuntu-mate.org/irc/) under their domain name. It is powered by Kiwi IRC client. Can we have a similar page, so that we can provide a direct link.
- Any suggestion for icon?
- Where all we need to include IRC icon? Both in community page and on footer, or just in community room?

**Comment by fossfreedom** [comment]
@GrindamN first bullet is for you

Maybe this for the Icon.

It should be in the community page with the explanation "if you disconnect..." as well as the footer.

**Comment by niyasc** [comment]
IRC link is added in Welcome App. Someone has to create a monochrome icon which matches with other social media icons. Current icon looks different from other icons.
![icon](https://cloud.githubusercontent.com/assets/2451833/22515941/41ebb2de-e8ca-11e6-8771-a218967672c9.png)

**Comment by fossfreedom** [comment]
@Foggalong please can you help with this one?

**Comment by Foggalong** [comment]
Yeah, sure thing. Are the sources for these icons stored in this repo also?

**Comment by fossfreedom** [comment]
thanks @Foggalong 

Udara created the other social icons you see in the picture above here - https://github.com/UbuntuBudgie/budgie-welcome/tree/master/data/img/social

**Comment by Foggalong** [comment]
@fossfreedom Cool cool, I'll get an IRC icon created either tonight or tomorrow morning :)
