### ISSUE TITLE
vimix theme

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#74]
vimix is a new material designed theme based on flat-plat

 - https://github.com/vinceliuice/vimix-gtk-themes

noobslab has packaged this - consider adding an option to one-click install this theme.

https://launchpad.net/~noobslab/+archive/ubuntu/themes?field.series_filter=zesty

**Comment by niyasc** [comment]
- Created option to switch to a material mode featuring vimix-gtk theme. Background, and icon theme remains same as existing material theme.

- Query - Is there any debugging mode enabled in recent xenial updates? I'm getting a lot of debugging messages when running welcome app.

**Comment by fossfreedom** [comment]
hmm --> I might have been debugging stuff and left some stray print messages. I'll need to look back at the last few commits to see where.
