### ISSUE TITLE
Key missing when installing chrome

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#75]
From memory whilst testing the app in zesty yesterday chrome appeared to fail to install.  Running an terminal update revealed a NO_PUBKEY message. 

Glitch? Or have we not included the chrome repo key when installing?

**Comment by niyasc** [comment]
Can you please check if following command is working?
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

If so, it  can be added in our `packages.json` file.

**Comment by fossfreedom** [comment]
sorry - just got around to retesting this on the latest zesty live CD - works great now!
