### ISSUE TITLE
Getting started navigation confusion

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#77]
I have seen a few videos now where people have clicked around the welcome app. One of the issues you see is that people click the back button thinking that is how to go back to the wizard.

So I would suggest for this screen we maybe change the navigation slightly. If you click the back button again when the options are displayed then just go back to the home screen. However, if you are in one of the getting started screens, the back button should first open the options slider.

Thoughts?

**Comment by niyasc** [comment]
Not a bad idea.

But what to do with existing toggle menu button? Remove it or keep as it is?

**Comment by fossfreedom** [comment]
Probably remove it since it would be redundant now


On 29 Jan 2017 05:23, Niyas C <notifications@github.com> wrote:

Not a bad idea.

But what to do with existing toggle menu button? Remove it or keep as it is?

**Comment by fossfreedom** [comment]
works really nice +1 :)
