### ISSUE TITLE
investigate alternative solution to work around 17.04 vs previous os differences

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#79]
niyasc : We can add an .official-only css class and show them only on official releases(17.04 and after). It can be used for #71 also

Sounds interesting - certainly will be better than the ugly javascript hacks we are using.

**Comment by HEXcube** [comment]
JavaScript'll still be needed to set the class, if release check is done at startup of Welcome app. Else, we could add a patch on packages for unofficial releases with something like:

```css
.offical-only {
    display: none;
}
```

Won't need JavaScript :relaxed:
