### ISSUE TITLE
Support snap and flatpak along apt packages

### ISSUE THREAD

**Issue by HEXcube** [UbuntuBudgie/budgie-welcome#85]
Looking at the code from https://github.com/UbuntuBudgie/budgie-welcome/blob/v0.3.12/data/config/packages.json: 

```js
"material-theme" : {
      "packages" : ["adapta-gtk-theme", "paper-cursor-theme", "paper-icon-theme"],
      "repos" : {
        "all" : ["ppa:snwh/pulp", "ppa:tista/adapta"]
      }
    }
```

the packages are all apt packages. A similar format'll have to be implemented for `snaps` n' `flatpaks`, something like:

```js
"kde-apps" : {
      "snaps" : ["kdenlive", "krita", "kid3"],
      "repos" : {
        "all" : ["KDE repo", "Ubuntu Snap repo"]
      }
    }
```

**Comment by fossfreedom** [comment]
Browser work previously in the 19.04 cycle covers the SNAP side.

Need to investigate further installing Flatpak + adding the Flatpak store
