### ISSUE TITLE
Google Chrome drops 32bit? 😕

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#91]
I read somewhere that Google Chrome does not have a 32bit version to install. Need to confirm this. If this is true, the Budgie Welcome's browser ballot should hide Google Chrome running on a 32bit platform.

**Comment by HEXcube** [comment]
Yep, seems you heard it right. See OMG!Ubuntu's post: [Link](http://www.omgubuntu.co.uk/2016/01/google-chrome-linux-32-bit-discontinued)

> "Google Chrome is to drop support for all 32-bit Linux distros from March, 2016"
