### ISSUE TITLE
rework recommendations to be compatible with translations

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#93]
from #89 Luke has done a massive amount of work to support translations - this is now in our translations branch.

Unfortunately the way the recommendations page is dynamically created is not compatible with how html pages are parsed to create translation .pot files and html files that are localised.

We are going to have to redo the recommendations - have all the recommendations moved back from the data/config/recommendations.json back into the recommendations.html.

To reorder the recommendations we are going to have to use a bit of javascript as described here

http://stackoverflow.com/questions/18785317/reorder-divs-based-on-element-attributes

for each recommendation we add an order attribute.  We change that value via python - the page should then (in theory) reorder via that javascript described in the answer http://stackoverflow.com/a/18785352/1626229

**Comment by lah7** [comment]
This is a similar problem that Ubuntu MATE Welcome has with its Software Boutique feature. It's not been resolved yet.

**Suggestions for alternate solutions:**

-----
Add localised strings in the JSON, such as:

    "name": {
        "fr": "Bonjour",
        "en": "Hello"
    }

Only downside is that translators need to know about this and have a basic understanding of JSON to avoid accidentally breaking the file. If these could be "converted" between POT/PO files, that would be good.

-----
The other (and easiest) is to "hard code" them in Python (as functions) which can be dynamically called. This wouldn't be too bad if it's not a lot of data. Anything put in `_("this function")` will be translatable in `budgie-welcome.pot`.

**Comment by fossfreedom** [comment]
superb!
