### ISSUE TITLE
Recommendations Backports not correctly showing whether installed or not

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#94]
Rather odd,

  the 17.04 recommendation to install our backports repo shows as available to be installed (i.e. in green) - however the PPA was already installed.

very odd.

**Comment by niyasc** [comment]
That is true. I was not able figure out a way to check whether repo is already installed or not. Grepping on source.list file seems not useful as it includes complete address of repository instead of shorthand notation like we used to add repository (`ppa:reposhorthand`).

**Comment by fossfreedom** [comment]
Shame - haven't found an API of any sort to help here.

Best I can think of is to test that the file /etc/apt/sources.list.d/xyz.list exists

so in our case ubuntubudge-ubuntu-backports-zesty.list

so the file to test is create via:

1. take the PPA name and split by "/" save in array
2. take first element of array append "-ubuntu-" + second element of array + "-" + distribution + ".list"

**Comment by fossfreedom** [comment]
@niyasc see any adverse issues with the above commit ?

**Comment by niyasc** [comment]
I don't see any issue right now. We just need to test it.
