### ISSUE TITLE
vimix is broken under 16.04 - need to remove it as an option

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#97]
need to retest/release the latest stuff on 16.04

Am aware the key areas of change are the theming - Vimix and Adapta.  Both need to be retested on 16.04.

In particular I remember I had to change the vimix packages for 17.04 - so may have to extend this area to cope with packaging changes between distro versions.

**Comment by niyasc** [comment]
- Adapta installation and styling went well without any issue.
- For vimix, theme names are different in 16.04 and 17.04. In 16.04, it is **vimix-light** and **vimix-dark**.

**Comment by fossfreedom** [comment]
ok - vimix is broken on 16.04 - panel and raven colours are broken.

Upstream vimix says in their readme they are only supporting gtk+3.20 and later.

Thus - vimix needs to be removed as an option from 16.04.

Need to find a way to-do this.
