### ISSUE TITLE
add estimated download/install time

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#98]
suggestion:
on start (in a separate python thread) we should measure the users download speed.

Then for each of the recommendations we already know the approximate size - so we should add just above the button text and estimated download and install time.

e.g. the themes are approx 30Mb - users on a slow network will just see a spinning circle for a long time.

**Comment by GrindamN** [comment]
I would add progress bar. Instead of showing circle, user could see progress bar with how much is left until theme is installed.

**Comment by niyasc** [comment]
This [answer](https://askubuntu.com/questions/104755/how-to-check-internet-speed-via-terminal) is *AskUbuntu* lists several methods for testing network speed. What can be a good choice?

**Comment by fossfreedom** [comment]
very nice find.  I installed `speedtest-cli` on 17.04 and this works really nicely - it returned "49.42 Mbit/s" for myself so it does cope with highspeed broadband.
