### ISSUE TITLE
Investigate ability to move app window on click-dragging headerbar

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#99]
Since Budgie Welcome doesn't have window decorations, the only way to move the app is via pressing the Super key or Alt key first before click-drag.

Lets investigate connecting webkit events to see if we can code a solution to move the app around via a regular mouse-click-drag on the pseudo headerbar.

**Comment by HEXcube** [comment]
Or would it be possible to add a real GTK3 CSD **headerbar** for the app and replace the current pseudo headerbar? :confused:

**Comment by fossfreedom** [comment]
sure - that's another way to go - the top part of each screen will need to be reworked.  e.g. status icon, navigation buttons need to be turned into real GTK buttons.  Top bar of each page need to be removed.

 But yeah - if its easier, definitely should be investigated.

**Comment by lah7** [comment]
I have some unused (but working) code from Ubuntu MATE Welcome that made a start with a CSD header (it was an experiment).

I've applied the changes in a branch of my fork of Budgie Welcome, which might be useful here.

* https://github.com/lah7/budgie-welcome/commit/c69a3cb349d8167e387e0c2dc4c23960216de9bd -- can pull request if desired?

**Comment by niyasc** [comment]
I don't have much idea about CSD **headerbar**. I hope it is something like *client side decoration* in GNOME Apps.

In my opinion, it is good to have a custom GTK headerbar instead of simulating header bar behavior with a pseudo header made with html/css.

Currently, we are showing/hiding progress button by javascript injection. If we go for a custom Gtk3 header, then we can do it natively.

**Comment by fossfreedom** [comment]
aye - CSD is indeed the decoration in GNOME Apps.

okey-dokey - we'll look at CSD then.  Thanks @lah7 - very useful, we should begin with your commit.

**Comment by HEXcube** [comment]
Saw the commit u made @lah7 : https://github.com/UbuntuBudgie/budgie-welcome/pull/101 . That's some pretty good work u did there. In addition to making the windows click-draggable, the window button position too follows the user setting now! :relaxed: Really useful for those who use left window buttons.

![Budgie Welcome with headerbar buttons on left](https://cloud.githubusercontent.com/assets/13032135/24354189/c86a267c-12e8-11e7-8d66-10b94c75f138.png)

Another request I've to make here is, would it be possible to use the symbolic logo instead of the currently used image. Symbolic icons'd change color to properly match the GTK theme - [Link to symbolic logo SVG](https://github.com/UbuntuBudgie/assets/blob/199e7fd4f6c4d0f363a486335506fe8e49eefc65/Logos/budgie-remix-symbolic.svg)

**Comment by niyasc** [comment]
I was thinking about a completely customized header as demonstrated in below video. May be, we can leave the close/maximize/minimize buttons natively as the initial commit made by @lah7 
https://youtu.be/3p1Kt1mAZKg

**Comment by HEXcube** [comment]
I'm rooting for native headerbar and buttons coz that'd naturally follow the system GTK theme (in our case, Arc) and have the additional benefit of respecting the user's button placement preference.

Cool video btw, Niyas! :+1: Which recorder are u using? Green Recorder or Peek? I'm curious :grin:

**Comment by fossfreedom** [comment]
A standard header bar would look odd because the colours of the app are fixed to arc. So nyasc has the right idea here ... A custom csd with the existing styling. Imho we can lose the custom close and leave with a standard min/close buttons​.

The even more complex idea would be to have standard themed header bars and somehow change the arc based app colours to respect the theme background colour.

Baby steps i think here is wise.

**Comment by niyasc** [comment]
> Cool video btw, Niyas! :+1: Which recorder are u using? Green Recorder or Peek? I'm curious :grin:

@HEXcube  
It is [**recordMyDesktop**](http://recordmydesktop.sourceforge.net/about.php)

**Comment by niyasc** [comment]
Current status
![screenshot from 2017-03-28 23-41-38](https://cloud.githubusercontent.com/assets/2451833/24420522/c2a0e75c-1410-11e7-9f8e-f2b4acb926a7.png)

@lah7 , Btw, I was not able to change position of window controls in **GtkHeader**. In fact, it was not working for any **CSD** enabled applications like *gedit*, *gnome-tweak-tool*, *nautilus* ..etc. While it was working with other applications like firefox, gnome-terminal ..etc. How did you manage to change it?

**Comment by HEXcube** [comment]
> Current status
![screenshot from 2017-03-28 23-41-38](https://cloud.githubusercontent.com/assets/2451833/24420522/c2a0e75c-1410-11e7-9f8e-f2b4acb926a7.png)

Looks cool, Niyas! :+1:

> Btw, I was not able to change position of window controls in **GtkHeader**. How did you manage to change it?

On my GNOME desktop, I used dconf-editor and edited a string to get left window buttons.

**Comment by HEXcube** [comment]
> A standard header bar would look odd because the colours of the app are fixed to arc

I don't think that'd be a problem, coz the default system theme too is the same - Arc. However, if the user tries a different theme, then the header'd look different.

> The even more complex idea would be to have standard themed header bars and somehow change the arc based app colours to respect the theme background colour

That looks like a longterm milestone. :relaxed: Shall I raise a separate issue?

**Comment by lah7** [comment]
> How did you manage to change it?

On my MATE desktop, I use MATE Tweak :grin: _(That changes a dconf setting somewhere)_

![image](https://cloud.githubusercontent.com/assets/13032135/24422498/a3190b40-13f1-11e7-99ad-6a658fd5975e.png)

By default, Ubuntu MATE (and Budgie) have window controls are on the right, However, I showed both as I like mine on the left, and to consider users who happen to change them on the left too.

I don't believe you can use GTK to force the position of the window's buttons, unless you take the custom button solution. I'm sure you _can_ add buttons to both the left and right sides of the CSD titlebar.

**Comment by HEXcube** [comment]
@lah7  Interesting, GNOME CSDs work properly on MATE! :smile:

@niyasc This issue on Solus ([Link](https://github.com/budgie-desktop/budgie-desktop/issues/716/))has a comment suggesting to install GNOME Tweak Tool first and then do the dconf setting change. On 17.04, that installs the *gnome-desktop-common* package too. I think it explains why the setting works afterwards. However, I couldn't get it to work on liveboot. :disappointed:

**Comment by fossfreedom** [comment]
![ubuntu budgie - new development snapshot 1 running - oracle vm virtualbox_737](https://cloud.githubusercontent.com/assets/996240/24479164/d4b01a6a-14d5-11e7-9e67-021473819141.png)

latest commit looks like this for me.

Changing the size-request to 1050 width works - but that is wider than some older displays that are 1024x768

setfocus on the button should be off.  Shouldnt this be on the right side ? (https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/HeaderBar.html#Gtk.HeaderBar.pack_end)

top arc-theme bar ("Main Menu") should now be removed - get the title from the current page and display in the headerbar set_title ?

**Comment by niyasc** [comment]
@fossfreedom Can you please make sure that **app.css** file is getting loaded properly? It is present in `/data/css/app.css`. Just add some random style and check whether it is appearing App or not.

In app.css, I have removed window border and shadow, to make sure that content area size remains the same. If content area is less, it will cause problem as you have shown in the screenshot.

**Comment by fossfreedom** [comment]
appears to be being loaded - just added some random text and on app startup the style_provider call for app.css failed.

**Comment by fossfreedom** [comment]
@niyasc fudged it ... set the zoom level to 0.95

**Comment by niyasc** [comment]
It appears that, for some reasons, custom css is not working in your system, and it is reason for
- Not showing content properly
- Different color for GtkHeader and Pseudo header,
- Different color for button on top left corner.
- Window border
- Drop shadow for window.

Can anyone run it on **Xenial**, to check whether it actually works in Xenial, or just me? Also, need to check for 16.10.

**Comment by fossfreedom** [comment]
aye - 16.04 working just fine (no need for the zoom level) - colours all fine - must be a GTK issue of some-sort - I'll check 16.10 later today.

**Comment by niyasc** [comment]
> aye - 16.04 working just fine (no need for the zoom level) - colours all fine - must be a GTK issue of some-sort - I'll check 16.10 later today.

Happy to hear that. :smile:  Then, we need to look for the root cause.

**Comment by fossfreedom** [comment]
@niyasc 

it is a CSS difference - changed from GTK+3.20 and later

I've got this far - not correct fully - but you get the idea

![untitled](https://cloud.githubusercontent.com/assets/996240/24512786/71cb013e-1567-11e7-857e-df0caf499648.png)

**Comment by niyasc** [comment]
Okey, Then I will try tweaking it in a Gtk 3.20+ platform.

**Comment by niyasc** [comment]
Moved **Status** button to GtkHeader. Now, the only thing remaining in pseudo header is page title (Main Menu/Recommendations/Chatrooms ..etc). Since, it is a part of HTML page, I was not able to figure out a way to retrieve it in python.

![screenshot from 2017-03-30 22-58-40](https://cloud.githubusercontent.com/assets/2451833/24517784/350714e6-159d-11e7-81b5-cd713aa1998f.png)

**Comment by fossfreedom** [comment]
https://lazka.github.io/pgi-docs/#WebKit2-4.0/classes/WebView.html#WebKit2.WebView.get_title

since we have the webview object - is the "main menu" etc set as the html title?

**Comment by niyasc** [comment]
Currently, we are not using title field in HTML pages.

Btw, I have updated app.css by live booting to Manjaro 17.0 (Gtk 3.22.1). Just check, whether it is working now.
![manjaor](https://cloud.githubusercontent.com/assets/2451833/24520550/6798fde0-1578-11e7-9c41-976127af00b4.png)

**Comment by fossfreedom** [comment]
yep - that has worked nicely.

Probably the title page is better from a maintenance point of view.  Looks like the translation stuff will be unaffected:
  
     <title>&zwnj;Introduction&zwnj;</title>

gets stored in data/i18n as 

    <title>Introduction</title>

**Comment by HEXcube** [comment]
> since we have the webview object - is the "main menu" etc set as the html title?

Like @fossfreedom requested, I think the current page name `Main Menu` should be moved from pseudo header and placed as subheading on headerbar. Like the GNOME Text Editor:

![text editor - headerbar subtitle](https://cloud.githubusercontent.com/assets/3755396/24581203/c51c4644-1734-11e7-930a-000a12f0552c.png)

I tweaked around the code a bit with the help of this Python GTK3 tutorial ([PythonGTK3](https://github.com/Programmica/python-gtk3-tutorial/blob/master/_examples/headerbar.py)) and inserted a

```python
 header.set_subtitle("HeaderBar Subtitle")
```

and got this:

![budgie welcome with subtitle](https://cloud.githubusercontent.com/assets/3755396/24581251/91f7f06e-1735-11e7-8223-dd11f4604525.png)

**Comment by HEXcube** [comment]
> Moved Status button to GtkHeader. Now, the only thing remaining in pseudo header is page title (Main Menu/Recommendations/Chatrooms ..etc). Since, it is a part of HTML page, I was not able to figure out a way to retrieve it in python.
> ![Budgie Welcome with Headerbar](https://cloud.githubusercontent.com/assets/2451833/24517784/350714e6-159d-11e7-81b5-cd713aa1998f.png)

@niyasc  How to get that `Status` button? :confused:  I couldn't get it from running the latest code. What's that button for?

**Comment by niyasc** [comment]
I have moved everything from pseudo header to GtkHeader. But it causes some issues as described in this commit. https://github.com/UbuntuBudgie/budgie-welcome/commit/2c1214fc1f2d67fadc52e3e0e6904fd8b96eeeee. We may have to stick with older approach till we tackle these issues.

---

> @niyasc How to get that Status button? :confused: I couldn't get it from running the latest code. What's that button for?

@HEXcube 
Status button will be visible when installation/removal task(s) are in progress. If we click on it, it will show a popup window listing currently active and pending installation/removal task(s)

---

> Like @fossfreedom requested, I think the current page name Main Menu should be moved from pseudo header. How about placing it as subheading on headerbar? Like the GNOME Text Editor:

I don't have any point against that approach. :smile:

**Comment by lah7** [comment]
I had a little test, just for curiosity -- here's some suggestions:

> Currently, we are using title change event to run commands on  python. When, we set title in each page, python get confused  whether it is a actionable event or just a page title

How about a JavaScript function instead? Such as:

    title?Name of page

That could be placed at the bottom of HTML pages in `<script>` tags, then add an `if` in `_do_command` to set the GTK label.

With the latest master, I couldn't actually see a page title in the CSD header. :thinking: 

---------
Another solution may be to set the title in `_load_changed_cb` based on which HTML file is loaded. This still supports translations using `gettext`, e.g.

```
if app.current_page == "index.html":
    self.page_title.set_label(_("Main Menu"))
elif app.current_page == "community.html":
    self.page_title.set_label(_("Community"))
```

---------
On slight quirk I noticed on my system (16.04, MATE, Ambiance-Colours theme) is that there's 2 pixel difference when the back button appears/disappears... a bit jarring... could just be my theme?

![image](https://cloud.githubusercontent.com/assets/13032135/24586184/92f9cfa2-1792-11e7-8fdb-cf85bc53428e.png)

Instead of hiding, you could disable the button using  `.set_sensitive(True)` or  `.set_sensitive(False)`.

**Comment by HEXcube** [comment]
> @lah7 , Btw, I was not able to change position of window controls in GtkHeader. In fact, it was not working for any CSD enabled applications like gedit, gnome-tweak-tool, nautilus ..etc. While it was working with other applications like firefox, gnome-terminal ..etc. How did you manage to change it?

@niyasc  I tried the gsettings config suggested by @fossfreedom to a user on Gitter community room and got left window buttons! :smiley: Try this command:

```gsettings set  org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/ShellShowsMenubar': <1>, 'Gtk/DecorationLayout': <'close,minimize,maximize,menu:'>}"```

**Comment by niyasc** [comment]
> gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'close,minimize,maximize,menu:'>}"

Cool. :+1: But that works for CSD enabled applications only. For the rest, we may have to following dconf settings only.

**Comment by HEXcube** [comment]
> Cool.  But that works for CSD enabled applications only. For the rest, we may have to following dconf settings only.

@niyasc Well, then we've to set both the keys:

```sh
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'close,minimize,maximize,menu:'>}"
gsettings set com.solus-project.budgie-wm button-layout 'close,maximize,minimize,appmenu:'
```

**Comment by fossfreedom** [comment]
Do you guys think this is a wildly wanted feature (left vs right buttons)?  if so, just create a separate issue (with the solution above) and we should add it somewhere (default settings?)

**Comment by HEXcube** [comment]
Yeah, I think it's a popular feature. :relaxed: Especially for users migrating from _Unity 7_.

**Comment by fossfreedom** [comment]
happy with this :)
